apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdfgfg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gdfgfg
  template:
    metadata:
      labels:
        app: gdfgfg
    spec:
      containers:
      - image: okteto.dev/gdfgfg:latest
        name: gdfgfg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "f80d184a-ea0d-4a38-bb87-54401bbe97f8"
        - name: Vless_Path
          value: "/vl5sdf55"
        - name: Vmess_UUID
          value: "f80d184a-ea0d-4a38-bb87-54401bbe97f8"
        - name: Vmess_Path
          value: "/vm6fd66"
        - name: Share_Path
          value: "/v2link"
